baseURL = "/"
languageCode = "pt-br"
title = "The Last Question"
description = "teste"
theme = "hugo-swift-theme"
canonifyurls = true
paginate = 4
disqusShortname: 'jeyziel-github-io'

[params]
    #blogDir = "posts"