baseURL = "/"
languageCode = "pt-br"
title = "J.S GAMA"
description = "teste"
theme = "hugo-swift-theme"
canonifyurls = true
paginate = 4
disqusShortname = 'jeyziel-github-io'

[permalinks]
  post = "/:slug/"


[params]
    #blogDir = "posts"